/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Mimics the behavior of `crypto.randomFillSync` from Node.js. */
export declare function randomFillSync(buffer: Buffer, offset?: number | undefined | null, length?: number | undefined | null): void
export declare function randomFillSyncNew(buffer: Buffer, offset?: number | undefined | null, length?: number | undefined | null): void
